import * as THREE from 'three';
import { AbstractPlantConfig } from './AbstractPlant';

export interface PlantPresetDictionary {
    [key: string]: AbstractPlantConfig;
}

export const avocadoSapling: AbstractPlantConfig = {
    maxHeight: 4,
    trunkThickness: 0.18,
    trunkTaper: 0.35,
    branchLevels: 3,
    branchesPerLevel: 3,
    branchAngle: 35,
    branchLength: 0.55,
    branchCurve: 0.15,
    branchThickness: 0.28,
    branchThicknessFalloff: 0.65,
    branchAtApex: true,
    branchChildren: {
        levels: 1,
        branchesPerLevel: 2,
        lengthScale: 0.6,
        thicknessScale: 0.6,
        angle: 22,
        spread: 40,
        curve: 0.05,
        leafScale: 0.65,
    },
    roots: {
        enabled: true,
        count: 5,
        length: 0.35,
        thickness: 0.45,
        taper: 0.6,
        spread: 0.55,
        flareHeight: 0.08,
    },
    leafShape: 'ellipsoid',
    leafSize: 0.55,
    leafCount: 24,
    leafDistribution: 'opposite',
    leafColor: new THREE.Color(0x3d8c45),
    flowers: {
        enabled: true,
        petalCount: 5,
        size: 0.3,
        color: new THREE.Color(0xfff3c9),
        position: 'branches',
    },
    fruit: {
        enabled: true,
        shape: 'ellipsoid',
        size: 0.45,
        color: new THREE.Color(0x3f3324),
        count: 4,
    },
    glow: {
        enabled: false,
        intensity: 0,
        color: new THREE.Color(0x000000),
    },
    crystals: {
        enabled: false,
        size: 0,
        count: 0,
        color: new THREE.Color(0x000000),
        placement: ['trunk'],
    },
    trunkColor: new THREE.Color(0x5b3a29),
    trunkMetallic: 0.05,
    trunkRoughness: 0.75,
};

export const glowShroom: AbstractPlantConfig = {
    maxHeight: 2.8,
    trunkThickness: 0.35,
    trunkTaper: 0.1,
    branchLevels: 1,
    branchesPerLevel: 6,
    branchAngle: 65,
    branchLength: 0.35,
    branchCurve: 0.6,
    branchThickness: 0.2,
    branchThicknessFalloff: 0.8,
    branchAtApex: true,
    branchChildren: {
        levels: 1,
        branchesPerLevel: 3,
        lengthScale: 0.5,
        thicknessScale: 0.55,
        angle: 30,
        spread: 60,
        curve: 0.2,
        leafScale: 0.7,
    },
    roots: {
        enabled: true,
        count: 6,
        length: 0.45,
        thickness: 0.35,
        taper: 0.5,
        spread: 0.75,
        flareHeight: 0.12,
    },
    leafShape: 'cone',
    leafSize: 0.4,
    leafCount: 36,
    leafDistribution: 'whorled',
    leafColor: new THREE.Color(0x92f9ff),
    flowers: {
        enabled: false,
        petalCount: 0,
        size: 0,
        color: new THREE.Color(0x000000),
        position: 'top',
    },
    fruit: {
        enabled: false,
        shape: 'sphere',
        size: 0,
        color: new THREE.Color(0x000000),
        count: 0,
    },
    glow: {
        enabled: true,
        intensity: 1.4,
        color: new THREE.Color(0x5ae5ff),
    },
    crystals: {
        enabled: true,
        size: 0.35,
        count: 5,
        color: new THREE.Color(0x4bd1ff),
        placement: ['trunk', 'roots'],
    },
    trunkColor: new THREE.Color(0x2d1f58),
    trunkMetallic: 0.35,
    trunkRoughness: 0.35,
};

export const crystalFern: AbstractPlantConfig = {
    maxHeight: 3.5,
    trunkThickness: 0.22,
    trunkTaper: 0.45,
    branchLevels: 4,
    branchesPerLevel: 4,
    branchAngle: 55,
    branchLength: 0.7,
    branchCurve: 0.4,
    branchThickness: 0.22,
    branchThicknessFalloff: 0.6,
    branchAtApex: true,
    branchChildren: {
        levels: 2,
        branchesPerLevel: 2,
        lengthScale: 0.58,
        thicknessScale: 0.55,
        angle: 28,
        spread: 55,
        curve: 0.18,
        leafScale: 0.65,
    },
    roots: {
        enabled: true,
        count: 8,
        length: 0.4,
        thickness: 0.32,
        taper: 0.5,
        spread: 0.6,
        flareHeight: 0.1,
    },
    leafShape: 'spiky',
    leafSize: 0.5,
    leafCount: 48,
    leafDistribution: 'spiral',
    leafColor: new THREE.Color(0x8cf5ff),
    flowers: {
        enabled: false,
        petalCount: 0,
        size: 0,
        color: new THREE.Color(0x000000),
        position: 'top',
    },
    fruit: {
        enabled: false,
        shape: 'cluster',
        size: 0,
        color: new THREE.Color(0x000000),
        count: 0,
    },
    glow: {
        enabled: true,
        intensity: 0.9,
        color: new THREE.Color(0x97f2ff),
    },
    crystals: {
        enabled: true,
        size: 0.28,
        count: 8,
        color: new THREE.Color(0xa0f3ff),
        placement: ['branches', 'trunk'],
    },
    trunkColor: new THREE.Color(0x214c58),
    trunkMetallic: 0.6,
    trunkRoughness: 0.25,
};

export const tentaclePlant: AbstractPlantConfig = {
    maxHeight: 5.5,
    trunkThickness: 0.16,
    trunkTaper: 0.2,
    branchLevels: 3,
    branchesPerLevel: 5,
    branchAngle: 75,
    branchLength: 0.9,
    branchCurve: -0.6,
    branchThickness: 0.18,
    branchThicknessFalloff: 0.55,
    branchAtApex: false,
    branchChildren: {
        levels: 2,
        branchesPerLevel: 3,
        lengthScale: 0.65,
        thicknessScale: 0.5,
        angle: 32,
        spread: 70,
        curve: -0.15,
        leafScale: 0.6,
    },
    roots: {
        enabled: true,
        count: 4,
        length: 0.5,
        thickness: 0.28,
        taper: 0.45,
        spread: 0.8,
        flareHeight: 0.06,
    },
    leafShape: 'cone',
    leafSize: 0.35,
    leafCount: 30,
    leafDistribution: 'spiral',
    leafColor: new THREE.Color(0xd661ff),
    flowers: {
        enabled: true,
        petalCount: 8,
        size: 0.6,
        color: new THREE.Color(0xff94ef),
        position: 'top',
    },
    fruit: {
        enabled: true,
        shape: 'cluster',
        size: 0.6,
        color: new THREE.Color(0xfe6add),
        count: 6,
    },
    glow: {
        enabled: true,
        intensity: 0.7,
        color: new THREE.Color(0xfd4bd1),
    },
    crystals: {
        enabled: false,
        size: 0,
        count: 0,
        color: new THREE.Color(0x000000),
        placement: ['branches'],
    },
    trunkColor: new THREE.Color(0x4e2f6c),
    trunkMetallic: 0.25,
    trunkRoughness: 0.45,
};

export const geometricTree: AbstractPlantConfig = {
    maxHeight: 6,
    trunkThickness: 0.24,
    trunkTaper: 0.55,
    branchLevels: 4,
    branchesPerLevel: 4,
    branchAngle: 40,
    branchLength: 0.6,
    branchCurve: 0,
    branchThickness: 0.24,
    branchThicknessFalloff: 0.7,
    branchAtApex: true,
    branchChildren: {
        levels: 2,
        branchesPerLevel: 2,
        lengthScale: 0.62,
        thicknessScale: 0.58,
        angle: 20,
        spread: 35,
        curve: 0,
        leafScale: 0.65,
    },
    roots: {
        enabled: true,
        count: 6,
        length: 0.38,
        thickness: 0.36,
        taper: 0.55,
        spread: 0.5,
        flareHeight: 0.07,
    },
    leafShape: 'sphere',
    leafSize: 0.75,
    leafCount: 32,
    leafDistribution: 'whorled',
    leafColor: new THREE.Color(0x67c7ff),
    flowers: {
        enabled: false,
        petalCount: 0,
        size: 0,
        color: new THREE.Color(0x000000),
        position: 'top',
    },
    fruit: {
        enabled: true,
        shape: 'sphere',
        size: 0.5,
        color: new THREE.Color(0xffd15f),
        count: 5,
    },
    glow: {
        enabled: true,
        intensity: 0.4,
        color: new THREE.Color(0x98f0ff),
    },
    crystals: {
        enabled: true,
        size: 0.4,
        count: 4,
        color: new THREE.Color(0xffffff),
        placement: ['trunk', 'branches', 'roots'],
    },
    trunkColor: new THREE.Color(0x2a2a33),
    trunkMetallic: 0.5,
    trunkRoughness: 0.2,
};

export const PLANT_PRESETS: PlantPresetDictionary = {
    avocadoSapling,
    glowShroom,
    crystalFern,
    tentaclePlant,
    geometricTree,
};

