export const WATER_RESERVOIR_CAPACITY = 1;
export const WATER_RESERVOIR_REFILL_DELAY_MS = 1800;
export const WATER_RESERVOIR_REFILL_RATE_PER_SECOND = 0.2;
export const WATER_RESERVOIR_MIN_LEVEL = 0;

export const WATER_DRAIN_RATE_PER_SECOND = 0.1;
export const WATER_APPLICATION_RADIUS_TILES = 0.2;

export const WATER_PLANT_FULL_THRESHOLD = 1;
export const WATER_PLANT_GROWTH_MULTIPLIER = 5;
export const WATER_PLANT_DECAY_RATE_PER_SECOND = 0.005;
export const WATER_PLANT_ABSORB_MULTIPLIER = 5;

export const WATER_DROPLET_EMIT_INTERVAL_MS = 60;
export const WATER_DROPLET_LIFETIME_MS = 820;

